apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vagas-monitor-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Update the CronJob to use the persistent volume
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vagas-monitor
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vagas-monitor
            image: your-registry/vagas-monitor:latest
            envFrom:
            - secretRef:
                name: vagas-monitor-secrets
            volumeMounts:
            - name: cache-volume
              mountPath: /app/data
          volumes:
          - name: cache-volume
            persistentVolumeClaim:
              claimName: vagas-monitor-cache
          restartPolicy: OnFailure
