apiVersion: batch/v1
kind: CronJob
metadata:
  name: vagas-monitor
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vagas-monitor
            image: your-registry/vagas-monitor:latest
            envFrom:
            - secretRef:
                name: vagas-monitor-secrets
          restartPolicy: OnFailure
