apiVersion: batch/v1
kind: CronJob
metadata:
  name: vagas-monitor
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vagas-monitor
            image: your-registry/vagas-monitor:latest
            envFrom:
            - secretRef:
                name: vagas-monitor-secrets
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Secret
metadata:
  name: vagas-monitor-secrets
type: Opaque
stringData:
  TWILIO_ACCOUNT_SID: "your-account-sid"
  TWILIO_AUTH_TOKEN: "your-auth-token"
  TWILIO_MESSAGING_SERVICE_SID: "your-messaging-service-sid"
  TWILIO_TO_NUMBER: "your-phone-number"
